---
# ansible-galaxy collection install -r requirements.yml --ignore-certs
# ansible-galaxy role install -r requirements.yml  --ignore-certs
roles:
  - name: mpatron.swap
    version: "1.2.1"
  - name: geerlingguy.gitlab
    version: "3.2.0"
  - name: roles-ansible.gitea
    version: "v3.6.2"
collections:
  - name: freeipa.ansible_freeipa
    source: https://galaxy.ansible.com
    # src: https://github.com/freeipa/ansible-freeipa.git
    version: ">=1.11.0"
  - name: community.general
    source: https://galaxy.ansible.com
    version: ">=7.5.0"
  - name: community.crypto
    source: https://galaxy.ansible.com
    version: ">=2.16.0"
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: ">=1.5.4"
  - name: community.postgresql
    source: https://galaxy.ansible.com
    version: ">=3.4.1"
