---
# handlers file for gitlab
- name: Restart gitlab
  ansible.builtin.systemd:
    name: gitlab-runsvdir
    state: restarted

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
