---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

- name: Install IPA clients
  hosts: ipaclients
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
