---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
#  vars:
#    generic_password: "HelloWorld1"
#    generic_domain: "jobjects.net"
#    generic_realm: "JOBJECTS.NET"
  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present
      vars:
        ipaserver_setup_dns: true
        ipaserver_auto_forwarders: true
        ipaserver_forwarders:
          - 8.8.8.8
          - 1.1.1.1
        ipaadmin_password: "{{ generic_password }}"
        ipadm_password: "{{ generic_password }}"
        ipaserver_domain: "{{ generic_domain }}"
        ipaserver_realm: "{{ generic_realm }}"

  tasks:
    - name: Set IPA domain config
      freeipa.ansible_freeipa.ipaconfig:
        ipaadmin_password: "{{ generic_password }}"
        enable_sid: true
        ipadefaultloginshell: "/bin/bash"
    # Install IPA Groupes
    - name: Include groups_present.json
      ansible.builtin.include_vars:
        file: groups_present.json
    - name: Groups present
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ generic_password }}"
        groups: "{{ groups_present }}"
    # Install IPA Users
    - name: Include users_present.json
      ansible.builtin.include_vars:
        file: users_present.json
    - name: Users present
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ generic_password }}"
        users: "{{ users_present }}"
    # Add me
    - name: Create me on FreeIPA
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ generic_password }}"
        name: mpatron
        first: Mickael
        last: Patron
        title: "Mr"
        displayname: "Mickael Patron"
        password: "{{ generic_password }}"
        update_password: on_create
    - name: Add to me the admins group
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ generic_password }}"
        name: admins
        action: member
        user:
          - mpatron
    - name: Add to me the wheel group
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ generic_password }}"
        name: wheel
        action: member
        user:
          - mpatron
    # Install IPA Groupes
    - name: Include groups_present.json
      ansible.builtin.include_vars:
        file: groups_present.json
    - name: Groups present
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ generic_password }}"
        groups: "{{ groups_present }}"
    # Install IPA Users
    - name: Include users_present.json
      ansible.builtin.include_vars:
        file: users_present.json
    - name: Users present
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ generic_password }}"
        users: "{{ users_present }}"
        password: "{{ generic_password }}"
        update_password: "on_create"

- name: Install IPA clients
  hosts: scm.jobjects.net
  become: true
  pre_tasks:
  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
      vars:
        ipaadmin_password: "{{ generic_password }}"
        ipaclient_mkhomedir: true
        ipaclient_subid: true
        ipaclient_server: "idm.jobjects.net"
        ipaclient_domain: "{{ generic_domain }}"
        ipaclient_realm: "{{ generic_realm }}"
        ipaclient_configure_dns_resolver: true
        ipaclient_dns_servers: "192.168.56.110"
  tasks:
#    # Add scm
#    - name: Create scm account on FreeIPA
#      freeipa.ansible_freeipa.ipauser:
#        ipaadmin_password: "{{ generic_password }}"
#        name: scm
#        first: Source
#        last: ControlManager
#        title: "Mr"
#        displayname: "SCM"
#        password: "{{ generic_password }}"
#        update_password: on_create
#    - name: Essais de connection
#      become: true
#      become_user: scm
#      ansible.builtin.shell: id

- name: Install SCM
  hosts: scm.jobjects.net
  become: true
  pre_tasks:
    - name: Adding users scm
      ansible.builtin.user:
        name: "scm"
        shell: "/bin/bash"
        password: "{{ generic_password | password_hash('sha512') }}" # NE FONCTIONNE PAS CAR PAS DE passlib
        create_home: true
        force: true
        update_password: on_create
        # echo $(mkpasswd --method=sha-512 'demo')
        # password: "$6$DkvtO7X1xjcHZ0LH$.1n5ahdjK1gZ8z7H6K0q6l9LU3Qte7CLpk9CVOTfpgdHq0M/o5aSyMlyXi49GPfzhQV2sEC0x2ald97o06UvW1"
        groups: "wheel"
        append: true

  roles:
    - role: roles-ansible.gitea
      tags: gitea
      state: present
      vars:
        gitea_fqdn: "scm.jobjects.net"
        gitea_root_url: "http://scm.jobjects.net"
        gitea_http_listen: "0.0.0.0"
        gitea_protocol: http
        gitea_start_ssh: true
        gitea_user: scm
  tasks:
