---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

  tasks:
    # Install IPA Groupes
    - name: Include groups_present.json
      ansible.builtin.include_vars:
        file: groups_present.json
    - name: Groups present
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        groups: "{{ groups_present }}"
    # Install IPA Users
    - name: Include users_present.json
      ansible.builtin.include_vars:
        file: users_present.json
    - name: Users present
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        users: "{{ users_present }}"
    # Add me
    - name: Create me on FreeIPA
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: mpatron
        first: Mickael
        last: Patron
        title: "Mr"
        displayname: "Mickael Patron"
        password: "{{ ipaadmin_password }}"
        update_password: on_create
    - name: Add to me the admins group
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: admins
        action: member
        user:
        - mpatron        
    - name: Add to me the wheel group
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: wheel
        action: member
        user:
        - mpatron        


- name: Install IPA clients
  hosts: ipaclients
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
    - role: gitlab
      state: present

